---
# Labeler configuration for Metal Compute Kernels

# Map labels to keywords in issues or paths in PRs

bug:
  - 'bug'
  - 'fix'

feature:
  - 'feature'
  - 'add'

perf:
  - 'perf'
  - 'performance'

docs:
  - 'docs'
  - 'documentation'

test:
  - 'test'
  - 'tests'

refactor:
  - 'refactor'
  - 'cleanup'

question:
  - 'question'

discussion:
  - 'discussion'

'good first issue':
  - 'good first issue'

'help wanted':
  - 'help wanted'

RNN:
  - 'LSTM'
  - 'GRU'

Transformer:
  - 'attention'
  - 'transformer'

Quantization:
  - 'quantization'

Physics:
  - 'physics'

iOS:
  - 'iOS'

macOS:
  - 'macOS'

tvOS:
  - 'tvOS'
